global:
  environment: development

backend:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"

frontend:
  replicas: 1
  resources:
    requests:
      memory: "32Mi"
      cpu: "25m"

postgres:
  credentials:
    password: "dev-password"

ingress:
  enabled: true
  className: nginx
  host: devops-portfolio.dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: ""
